# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demoDatabase.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 92, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEditDBName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditDBName.setGeometry(QtCore.QRect(250, 99, 231, 41))
        self.lineEditDBName.setObjectName("lineEditDBName")
        self.labelResponse = QtWidgets.QLabel(self.centralwidget)
        self.labelResponse.setGeometry(QtCore.QRect(70, 240, 511, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelResponse.setFont(font)
        self.labelResponse.setText("")
        self.labelResponse.setObjectName("labelResponse")
        self.pushButtonCreateDB = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonCreateDB.setGeometry(QtCore.QRect(220, 182, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonCreateDB.setFont(font)
        self.pushButtonCreateDB.setObjectName("pushButtonCreateDB")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Enter Database Name:"))
        self.pushButtonCreateDB.setText(_translate("MainWindow", "Create Database"))
