# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demoCreateTable.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(725, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 50, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEditDBName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditDBName.setGeometry(QtCore.QRect(240, 40, 291, 41))
        self.lineEditDBName.setObjectName("lineEditDBName")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 120, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEditTableName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditTableName.setGeometry(QtCore.QRect(240, 110, 291, 41))
        self.lineEditTableName.setObjectName("lineEditTableName")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 210, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(250, 210, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pushButtonAddColumn = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonAddColumn.setGeometry(QtCore.QRect(500, 250, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonAddColumn.setFont(font)
        self.pushButtonAddColumn.setObjectName("pushButtonAddColumn")
        self.lineEditColumnName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditColumnName.setGeometry(QtCore.QRect(40, 250, 201, 31))
        self.lineEditColumnName.setObjectName("lineEditColumnName")
        self.comboBoxDataType = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxDataType.setGeometry(QtCore.QRect(270, 251, 201, 31))
        self.comboBoxDataType.setObjectName("comboBoxDataType")
        self.pushButtonCreateTable = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonCreateTable.setGeometry(QtCore.QRect(280, 340, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonCreateTable.setFont(font)
        self.pushButtonCreateTable.setObjectName("pushButtonCreateTable")
        self.labelResponse = QtWidgets.QLabel(self.centralwidget)
        self.labelResponse.setGeometry(QtCore.QRect(130, 400, 391, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelResponse.setFont(font)
        self.labelResponse.setText("")
        self.labelResponse.setObjectName("labelResponse")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 725, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Enter Database Name"))
        self.label_2.setText(_translate("MainWindow", "Enter Table Name"))
        self.label_3.setText(_translate("MainWindow", "Column Name"))
        self.label_4.setText(_translate("MainWindow", "Data Type"))
        self.pushButtonAddColumn.setText(_translate("MainWindow", "Add Column"))
        self.pushButtonCreateTable.setText(_translate("MainWindow", "Create Table"))
