# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demoSlider.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 480)
        font = QtGui.QFont()
        font.setPointSize(14)
        Dialog.setFont(font)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(70, 70, 111, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(70, 110, 131, 41))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(70, 150, 91, 41))
        self.label_3.setObjectName("label_3")
        self.horizontalScrollBarSugarLevel = QtWidgets.QScrollBar(Dialog)
        self.horizontalScrollBarSugarLevel.setGeometry(QtCore.QRect(220, 80, 351, 21))
        self.horizontalScrollBarSugarLevel.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBarSugarLevel.setObjectName("horizontalScrollBarSugarLevel")
        self.horizontalSliderPulseRate = QtWidgets.QSlider(Dialog)
        self.horizontalSliderPulseRate.setGeometry(QtCore.QRect(220, 130, 351, 22))
        self.horizontalSliderPulseRate.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderPulseRate.setObjectName("horizontalSliderPulseRate")
        self.verticalScrollBarBloodPressure = QtWidgets.QScrollBar(Dialog)
        self.verticalScrollBarBloodPressure.setGeometry(QtCore.QRect(200, 170, 16, 211))
        self.verticalScrollBarBloodPressure.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBarBloodPressure.setObjectName("verticalScrollBarBloodPressure")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(340, 160, 131, 21))
        self.label_4.setObjectName("label_4")
        self.verticalSliderCholestLevel = QtWidgets.QSlider(Dialog)
        self.verticalSliderCholestLevel.setGeometry(QtCore.QRect(490, 170, 22, 160))
        self.verticalSliderCholestLevel.setOrientation(QtCore.Qt.Vertical)
        self.verticalSliderCholestLevel.setObjectName("verticalSliderCholestLevel")
        self.lineEditResult = QtWidgets.QLineEdit(Dialog)
        self.lineEditResult.setGeometry(QtCore.QRect(150, 410, 331, 31))
        self.lineEditResult.setObjectName("lineEditResult")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Sugar Level"))
        self.label_2.setText(_translate("Dialog", "Blood Pressure"))
        self.label_3.setText(_translate("Dialog", "Pulse Rate"))
        self.label_4.setText(_translate("Dialog", "Cholestrol Level"))
